import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { FlickeringGrid } from "@/components/ui/flickering-grid";

const jetbrainsMono = JetBrains_Mono({
	subsets: ["latin"],
	variable: "--font-sans",
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={jetbrainsMono.variable}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
			>
				{/* Flickering Grid Background */}
				<div className="fixed inset-0 z-0 overflow-hidden">
					<FlickeringGrid
						className="w-full h-full"
						squareSize={4}
						gridGap={6}
						color="#6B7280"
						maxOpacity={0.5}
						flickerChance={0.1}
					/>
				</div>
				{/* Content */}
				<div className="relative z-10">
					{children}
				</div>
			</body>
		</html>
	);
}
